[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_NPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For serverless functions
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# For handling Next.js routes properly
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
