[build]
  command = "echo 'Skipping build process'"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  NETLIFY_USE_NPM = "true"
