name: Update pnpm lockfile

on:
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          
      - name: Update lockfile
        run: pnpm install --no-frozen-lockfile
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update pnpm-lock.yaml"
          file_pattern: pnpm-lock.yaml
